jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
        url: https://github.com/Fabio-Klinge/DreamerV2-final_project-DRL.git
  DreamerV2:
    resources:
      instance-type: C4
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
        model:
            type: volume
    uses: script@v1
    with:
      script: |-
        cd /inputs/repo
        pip install -r requirements.txt
        wandb login fe6d76dd59b168f3c38dc3200555a6f9b3169b73
        python main.py
      image: tensorflow/tensorflow:latest-gpu
